(ns lmgrep.predefined-analyzers
  (:require [lmgrep.features])
  (:import (java.util Locale ArrayList)
           (java.text Collator)
           (org.apache.lucene.analysis.ar ArabicAnalyzer)
           (org.apache.lucene.analysis.bg BulgarianAnalyzer)
           (org.apache.lucene.analysis.bn BengaliAnalyzer)
           (org.apache.lucene.analysis.br BrazilianAnalyzer)
           (org.apache.lucene.analysis.ca CatalanAnalyzer)
           (org.apache.lucene.analysis.cjk CJKAnalyzer)
           (org.apache.lucene.analysis.ckb SoraniAnalyzer)
           (org.apache.lucene.analysis CharArraySet)
           (org.apache.lucene.analysis.core StopAnalyzer UnicodeWhitespaceAnalyzer WhitespaceAnalyzer KeywordAnalyzer SimpleAnalyzer)
           (org.apache.lucene.analysis.cz CzechAnalyzer)
           (org.apache.lucene.analysis.da DanishAnalyzer)
           (org.apache.lucene.analysis.nl DutchAnalyzer)
           (org.apache.lucene.analysis.de GermanAnalyzer)
           (org.apache.lucene.analysis.el GreekAnalyzer)
           (org.apache.lucene.analysis.es SpanishAnalyzer)
           (org.apache.lucene.analysis.et EstonianAnalyzer)
           (org.apache.lucene.analysis.eu BasqueAnalyzer)
           (org.apache.lucene.analysis.fa PersianAnalyzer)
           (org.apache.lucene.analysis.fi FinnishAnalyzer)
           (org.apache.lucene.analysis.fr FrenchAnalyzer)
           (org.apache.lucene.analysis.ga IrishAnalyzer)
           (org.apache.lucene.analysis.gl GalicianAnalyzer)
           (org.apache.lucene.analysis.hi HindiAnalyzer)
           (org.apache.lucene.analysis.hu HungarianAnalyzer)
           (org.apache.lucene.analysis.hy ArmenianAnalyzer)
           (org.apache.lucene.analysis.id IndonesianAnalyzer)
           (org.apache.lucene.analysis.it ItalianAnalyzer)
           (org.apache.lucene.analysis.lt LithuanianAnalyzer)
           (org.apache.lucene.analysis.lv LatvianAnalyzer)
           (org.apache.lucene.analysis.no NorwegianAnalyzer)
           (org.apache.lucene.analysis.pt PortugueseAnalyzer)
           (org.apache.lucene.analysis.ro RomanianAnalyzer)
           (org.apache.lucene.analysis.ru RussianAnalyzer)
           (org.apache.lucene.analysis.standard StandardAnalyzer)
           (org.apache.lucene.analysis.sv SwedishAnalyzer)
           (org.apache.lucene.analysis.th ThaiAnalyzer)
           (org.apache.lucene.analysis.tr TurkishAnalyzer)
           (org.apache.lucene.analysis.en EnglishAnalyzer)
           (org.apache.lucene.collation CollationKeyAnalyzer)
           (org.apache.lucene.analysis.classic ClassicAnalyzer)
           (org.apache.lucene.analysis.email UAX29URLEmailAnalyzer)))

(defn stempel-analyzers []
  (when lmgrep.features/stempel?
    (require '[lmgrep.stempel])
    @(resolve 'lmgrep.stempel/analyzers)))

(def analyzers
  (merge
    (stempel-analyzers)
    {"arabic"            (ArabicAnalyzer.)
    "bulgarian"         (BulgarianAnalyzer.)
    "bengali"           (BengaliAnalyzer.)
    "brazilian"         (BrazilianAnalyzer.)
    "catalan"           (CatalanAnalyzer.)
    "cjk"               (CJKAnalyzer.)
    "sorani"            (SoraniAnalyzer.)
    "stop"              (StopAnalyzer. (CharArraySet. (ArrayList.) true))
    "czech"             (CzechAnalyzer.)
    "danish"            (DanishAnalyzer.)
    "dutch"             (DutchAnalyzer.)
    "german"            (GermanAnalyzer.)
    "greek"             (GreekAnalyzer.)
    "spanish"           (SpanishAnalyzer.)
    "estonian"          (EstonianAnalyzer.)
    "basque"            (BasqueAnalyzer.)
    "persian"           (PersianAnalyzer.)
    "finnish"           (FinnishAnalyzer.)
    "french"            (FrenchAnalyzer.)
    "irish"             (IrishAnalyzer.)
    "galician"          (GalicianAnalyzer.)
    "hindi"             (HindiAnalyzer.)
    "hungarian"         (HungarianAnalyzer.)
    "armenian"          (ArmenianAnalyzer.)
    "indonesian"        (IndonesianAnalyzer.)
    "italian"           (ItalianAnalyzer.)
    "lithuanian"        (LithuanianAnalyzer.)
    "latvian"           (LatvianAnalyzer.)
    "norwegian"         (NorwegianAnalyzer.)
    "portuguese"        (PortugueseAnalyzer.)
    "romanian"          (RomanianAnalyzer.)
    "russian"           (RussianAnalyzer.)
    "classic"           (ClassicAnalyzer.)
    "uax29urlemail"     (UAX29URLEmailAnalyzer.)
    "swedish"           (SwedishAnalyzer.)
    "thai"              (ThaiAnalyzer.)
    "turkish"           (TurkishAnalyzer.)
    "english"           (EnglishAnalyzer.)
    "standard"          (StandardAnalyzer.)
    "unicodewhitespace" (UnicodeWhitespaceAnalyzer.)
    "whitespace"        (WhitespaceAnalyzer.)
    "keyword"           (KeywordAnalyzer.)
    "simple"            (SimpleAnalyzer.)
    "collationkey"      (CollationKeyAnalyzer. (Collator/getInstance Locale/ENGLISH))}))
