#!/usr/bin/env bash

set -eou pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

LMGREP_VERSION=$(cat resources/LMGREP_VERSION)

LMGREP_JAR=${LMGREP_JAR:-"target/lmgrep-uber.jar"}

if [[ ! -f "$LMGREP_JAR" ]]
then
    echo "Please run make uberjar first."
    exit 1
fi

args=( "-jar"
       "$LMGREP_JAR"
       "-H:Name=lmgrep"
       "--no-fallback"
       "--initialize-at-build-time"
       "-H:+ReportExceptionStackTraces"
       "-H:IncludeResources=LMGREP_VERSION"
       "-H:+AddAllCharsets"
       "-H:ReflectionConfigurationFiles=$(pwd)/graalvm/lucene-reflect-config.json" )

LMGREP_STATIC=${LMGREP_STATIC:-}
LMGREP_MUSL=${LMGREP_MUSL:-}

if [ "$LMGREP_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$LMGREP_MUSL" = "true" ]; then
        args+=("--libc=musl")
    fi
fi

LMGREP_FEATURE_RAUDIKKO=${LMGREP_FEATURE_RAUDIKKO:-}

if [ "$LMGREP_FEATURE_RAUDIKKO" = "true" ]; then
    args+=("-H:IncludeResources=morpho/.*")
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"

#upx -7 -k lmgrep
