#!/usr/bin/env bash

set -eou pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

LMGREP_VERSION=$(cat resources/LMGREP_VERSION)

LMGREP_JAR=${LMGREP_JAR:-"target/lmgrep.jar"}

if [[ ! -f "$LMGREP_JAR" ]]
then
    echo "Please run make uberjar first."
    exit 1
fi

args=( "-jar"
       "$LMGREP_JAR"
       "-H:Name=lmgrep"
       "--no-fallback"
       "--initialize-at-build-time"
       "-H:+ReportExceptionStackTraces"
       "-H:IncludeResources=LMGREP_VERSION"
       "-H:+BuildReport"
       "-march=native"
       "-H:ReflectionConfigurationFiles=$(pwd)/graalvm/lucene-reflect-config.json" )

LMGREP_STATIC=${LMGREP_STATIC:-}
LMGREP_MUSL=${LMGREP_MUSL:-}

if [ "$LMGREP_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$LMGREP_MUSL" = "true" ]; then
        args+=("--libc=musl")
    fi
fi

LMGREP_FEATURE_RAUDIKKO=${LMGREP_FEATURE_RAUDIKKO:-}

if [ "$LMGREP_FEATURE_RAUDIKKO" = "true" ]; then
    args+=("-H:IncludeResources=morpho/.*")
fi

LMGREP_FEATURE_CHARSETS=${LMGREP_FEATURE_CHARSETS:-}

if [ "$LMGREP_FEATURE_CHARSETS" = "true" ]; then
  args+=("-H:+AddAllCharsets")
fi

LMGREP_FEATURE_EPSILON_GC=${LMGREP_FEATURE_EPSILON_GC:-}

if [ "$LMGREP_FEATURE_EPSILON_GC" = "true" ]; then
  args+=("--gc=epsilon")
fi

LMGREP_DEV_BUILD=${LMGREP_DEV_BUILD:-}

if [ "$LMGREP_DEV_BUILD" = "true" ]; then
  args+=("-Ob")
fi

if [ "$LMGREP_FEATURE_BUNDLED_ANALYZERS" = "true" ]; then
  args+=("-ELMGREP_FEATURE_BUNDLED_ANALYZERS=true")
fi

if [ "$LMGREP_FEATURE_STEMPEL" = "true" ]; then
  args+=("-ELMGREP_FEATURE_STEMPEL=true")
fi

if [ "$LMGREP_FEATURE_SNOWBALL" = "true" ]; then
  args+=("-ELMGREP_FEATURE_SNOWBALL=true")
fi

if [ "$LMGREP_FEATURE_RAUDIKKO" = "true" ]; then
  args+=("-ELMGREP_FEATURE_RAUDIKKO=true")
fi

JAVA_VERSION=$(java -version 2>&1 | head -1 | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
if [[ $JAVA_VERSION =~ 19.* ]]; then
  echo "UWAGA: Java 19 on macOS doesn't support `enableMemorySegments`"
  args+=("-Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false")
fi

if [[ $JAVA_VERSION =~ 20.* ]]; then
  echo "UWAGA: Java 20 on macOS doesn't support `enableMemorySegments`"
  args+=("-Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false")
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}"

#upx -7 -k lmgrep
