#!/usr/bin/env bash

# Instructions from this page https://www.graalvm.org/reference-manual/native-image/StaticImages/#preparation

set -euo pipefail

MUSL_DIR=$(pwd)/.musl
MUSL_GCC_COMPILER=${MUSL_DIR}/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc

if [ -f "$MUSL_GCC_COMPILER" ]; then
    echo "MUSL is already setup at ${MUSL_DIR}"
    exit 0
fi

mkdir "$MUSL_DIR" || true

cd "$MUSL_DIR"

wget https://more.musl.cc/10.2.1/x86_64-linux-musl/x86_64-linux-musl-native.tgz

tar zxvf x86_64-linux-musl-native.tgz

TOOLCHAIN_DIR=$(pwd)/x86_64-linux-musl-native

CC=$TOOLCHAIN_DIR/bin/gcc

ZLIB_VERSION=1.2.13

wget https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz

tar zxvf zlib-${ZLIB_VERSION}.tar.gz

cd zlib-${ZLIB_VERSION}

./configure --prefix="$TOOLCHAIN_DIR" --static
make
make install

export PATH=$PATH:${TOOLCHAIN_DIR}/bin
