#!/usr/bin/env bash

# Instructions from this page https://www.graalvm.org/reference-manual/native-image/StaticImages/#preparation

set -euo pipefail

MUSL_DIR=$(pwd)/.musl
MUSL_GCC_COMPILER=${MUSL_DIR}/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc

if [ -f "$MUSL_GCC_COMPILER" ]; then
    echo "MUSL is already setup at ${MUSL_DIR}"
    exit 0
fi

mkdir "$MUSL_DIR" || true

cd "$MUSL_DIR"

wget http://musl.cc/x86_64-linux-musl-native.tgz

tar zxvf x86_64-linux-musl-native.tgz

TOOLCHAIN_DIR=$(pwd)/x86_64-linux-musl-native

CC=$TOOLCHAIN_DIR/bin/gcc

wget https://zlib.net/zlib-1.2.11.tar.gz

tar zxvf zlib-1.2.11.tar.gz

cd zlib-1.2.11

./configure --prefix="$TOOLCHAIN_DIR" --static
make
make install

export PATH=$PATH:${TOOLCHAIN_DIR}/bin
