name: Tests

on:
  push:

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Cache maven deps
        uses: actions/cache@v3.0.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.11.1.1155

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.9.161

      - name: Unit Tests
        env:
          LMGREP_FEATURE_BUNDLED_ANALYZERS: true
          LMGREP_FEATURE_STEMPEL: true
          LMGREP_FEATURE_SNOWBALL: true
          LMGREP_FEATURE_RAUDIKKO: true
        run: |
          clojure -T:build prep-deps
          bb test
