name: Tests

on:
  push:

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Cache maven deps
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: '1.11.1.1347'
          bb: '1.3.181'

      - name: Unit Tests
        env:
          LMGREP_FEATURE_BUNDLED_ANALYZERS: true
          LMGREP_FEATURE_STEMPEL: true
          LMGREP_FEATURE_SNOWBALL: true
          LMGREP_FEATURE_RAUDIKKO: true
        run: |
          bb deps-prep
          bb test
