name: Tests

on:
  push:

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.3.1069

      - name: Unit Tests
        env:
          LMGREP_FEATURE_BUNDLED_ANALYZERS: true
          LMGREP_FEATURE_STEMPEL: true
          LMGREP_FEATURE_SNOWBALL: true
          LMGREP_FEATURE_RAUDIKKO: true
        run: |
          clojure -T:build prep-deps
          clojure -M:dev:raudikko:snowball-token-filters:stempel:bundled-analyzers:test
