name: Tests

on:
  push:

env:
  BABASHKA_VERSION: '1.0.173'

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Cache maven deps
        uses: actions/cache@v3.2.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1208'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: ${{ env.BABASHKA_VERSION }}

      - name: Unit Tests
        env:
          LMGREP_FEATURE_BUNDLED_ANALYZERS: true
          LMGREP_FEATURE_STEMPEL: true
          LMGREP_FEATURE_SNOWBALL: true
          LMGREP_FEATURE_RAUDIKKO: true
        run: |
          clojure -T:build prep-deps
          bb test
