name: Tests

on:
  push:
    tags:
      - 't*'

jobs:

  test-tags-ogn-windows:
    runs-on: windows-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check tags usage
        run: |
          echo "test" > test-$($env:RELEASE_VERSION).txt
          dir
          echo ">>>>>>>>>>>>>"

  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.3.1069

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.4

      - name: Unit Tests
        env:
          LMGREP_FEATURE_BUNDLED_ANALYZERS: true
          LMGREP_FEATURE_STEMPEL: true
          LMGREP_FEATURE_SNOWBALL: true
          LMGREP_FEATURE_RAUDIKKO: true
        run: |
          clojure -T:build prep-deps
          bb test
